libUPnP: /Users/mylhyz/Downloads/libupnp-1.14.18/ixml/src/document.c File Reference
document.c File Reference
#include "ixmldebug.h"
#include "ixmlparser.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "posix_overwrites.h"
Functions
void ixmlDocument_init (IXML_Document *doc)
Initializes a Document node.
void ixmlDocument_free (IXML_Document *doc)
Frees a Document object and all Nodes associated with it.
static void ixmlDocument_setOwnerDocument (IXML_Document *doc, IXML_Node *nodeptr)
int ixmlDocument_importNode (IXML_Document *doc, IXML_Node *importNode, int deep, IXML_Node **rtNode)
Imports a Node from another Document into this Document.
int ixmlDocument_createElementEx (IXML_Document *doc, const char *tagName, IXML_Element **rtElement)
Creates a new Element node with the given tag name.
IXML_Element * ixmlDocument_createElement (IXML_Document *doc, const char *tagName)
Creates a new Element node with the given tag name.
int ixmlDocument_createDocumentEx (IXML_Document **rtDoc)
Creates a new empty Document node.
IXML_Document * ixmlDocument_createDocument ()
Creates a new empty Document node.
int ixmlDocument_createTextNodeEx (IXML_Document *doc, const char *data, IXML_Node **textNode)
Creates a new Text node with the given data.
IXML_Node * ixmlDocument_createTextNode (IXML_Document *doc, const char *data)
Creates a new Text node with the given data.
int ixmlDocument_createAttributeEx (IXML_Document *doc, const char *name, IXML_Attr **rtAttr)
Creates a new Attr node with the given name.
IXML_Attr * ixmlDocument_createAttribute (IXML_Document *doc, const char *name)
Creates a new Attr node with the given name.
int ixmlDocument_createAttributeNSEx (IXML_Document *doc, const char *namespaceURI, const char *qualifiedName, IXML_Attr **rtAttr)
Creates a new Attr node with the given qualified name and namespace URI.
IXML_Attr * ixmlDocument_createAttributeNS (IXML_Document *doc, const char *namespaceURI, const char *qualifiedName)
Creates a new Attribute node with the given qualified name and namespace URI.
int ixmlDocument_createCDATASectionEx (IXML_Document *doc, const char *data, IXML_CDATASection **rtCD)
Creates a new CDATASection node with given data.
IXML_CDATASection * ixmlDocument_createCDATASection (IXML_Document *doc, const char *data)
Creates a new CDATASection node with given data.
int ixmlDocument_createElementNSEx (IXML_Document *doc, const char *namespaceURI, const char *qualifiedName, IXML_Element **rtElement)
Creates a new Element node in the given qualified name and namespace URI.
IXML_Element * ixmlDocument_createElementNS (IXML_Document *doc, const char *namespaceURI, const char *qualifiedName)
Creates a new Element node in the given qualified name and namespace URI.
IXML_NodeList * ixmlDocument_getElementsByTagName (IXML_Document *doc, const char *tagName)
Returns a NodeList of all Elements that match the given tag name in the order in which they were encountered in a preorder traversal of the Document tree.
IXML_NodeList * ixmlDocument_getElementsByTagNameNS (IXML_Document *doc, const char *namespaceURI, const char *localName)
Returns a NodeList of Elements that match the given local name and namespace URI in the order they are encountered in a preorder traversal of the Document tree.
IXML_Element * ixmlDocument_getElementById (IXML_Document *doc, const char *tagName)
Returns the Element whose ID matches that given id.
Function Documentation
ixmlDocument_setOwnerDocument()
static void ixmlDocument_setOwnerDocument (IXML_Document * doc, IXML_Node * nodeptr) static
When this function is called first time, nodeptr is the root of the subtree, so it is not necessay to do two steps recursion.
Internal function called by ixmlDocument_importNode
Parameters
[in] doc The document node.
[in] nodeptr
Todo
documentation.
References ixmlDocument_setOwnerDocument(), ixmlNode_getFirstChild(), and ixmlNode_getNextSibling().
Referenced by ixmlDocument_importNode(), and ixmlDocument_setOwnerDocument().