libUPnP: /Users/mylhyz/Downloads/libupnp-1.14.18/upnp/src/inc/soaplib.h File Reference
soaplib.h File Reference
#include "sock.h"
Functions
void soap_device_callback (http_parser_t *parser, http_message_t *request, SOCKINFO *info)
This is a callback called by minisever after receiving the request from the control point. This function will start processing the request. It calls handle_invoke_action to handle the SOAP action.
int SoapSendAction (char *action_url, char *service_type, IXML_Document *action_node, IXML_Document **response_node)
int SoapSendActionEx (char *ActionURL, char *ServiceType, IXML_Document *Header, IXML_Document *ActNode, IXML_Document **RespNode)
int SoapGetServiceVarStatus (char *ActionURL, DOMString VarName, DOMString *StVar)
Variables
const char * ContentTypeHeader
Function Documentation
soap_device_callback()
void soap_device_callback (http_parser_t * parser, http_message_t * request, SOCKINFO * info)
This is a callback called by minisever after receiving the request from the control point. This function will start processing the request. It calls handle_invoke_action to handle the SOAP action.
This is a callback called by minisever after receiving the request from the control point. This function will start processing the request. It calls handle_invoke_action to handle the SOAP action.
Parameters
[in] parser Parsed request received by the device.
[in] request HTTP request.
info [in,out] Socket info.
References memptr::buf, check_soap_request(), check_soapaction_hdr(), http_message_t::entity, SOCKINFO::foreign_sockaddr, get_dev_service(), handle_invoke_action(), handle_query_variable(), has_xml_content_type(), ixmlDocument_free(), ixmlParseBufferEx(), UPNP_E_OUTOF_MEMORY, and UPNP_E_SUCCESS.
Referenced by UpnpInitPreamble().