libUPnP: /Users/mylhyz/Downloads/libupnp-1.14.18/upnp/src/ssdp/SSDPResultData.h File Reference
SSDPResultData.h File Reference
Header file for SSDPResultData methods.
#include <stdlib.h>
#include "UpnpGlobal.h"
#include "Callback.h"
#include "UpnpDiscovery.h"
Typedefs
typedef struct s_SSDPResultData SSDPResultData
Functions
UPNP_EXPORT_SPEC SSDPResultData * SSDPResultData_new ()
UPNP_EXPORT_SPEC void SSDPResultData_delete (SSDPResultData *p)
UPNP_EXPORT_SPEC SSDPResultData * SSDPResultData_dup (const SSDPResultData *p)
UPNP_EXPORT_SPEC int SSDPResultData_assign (SSDPResultData *p, const SSDPResultData *q)
UPNP_EXPORT_SPEC const UpnpDiscovery * SSDPResultData_get_Param (const SSDPResultData *p)
UPNP_EXPORT_SPEC int SSDPResultData_set_Param (SSDPResultData *p, const UpnpDiscovery *n)
UPNP_EXPORT_SPEC void * SSDPResultData_get_Cookie (const SSDPResultData *p)
UPNP_EXPORT_SPEC int SSDPResultData_set_Cookie (SSDPResultData *p, void *n)
UPNP_EXPORT_SPEC Upnp_FunPtr SSDPResultData_get_CtrlptCallback (const SSDPResultData *p)
UPNP_EXPORT_SPEC int SSDPResultData_set_CtrlptCallback (SSDPResultData *p, Upnp_FunPtr n)
Detailed Description
Header file for SSDPResultData methods.
Do not edit this file, it is automatically generated. Please look at generator.c.
Author
Marcelo Roberto Jimenez
Typedef Documentation
SSDPResultData
typedef struct s_SSDPResultData SSDPResultData
SSDPResultData
Function Documentation
SSDPResultData_assign()
UPNP_EXPORT_SPEC int SSDPResultData_assign (SSDPResultData * p, const SSDPResultData * q)
Assignment operator
References SSDPResultData_get_Cookie(), SSDPResultData_get_CtrlptCallback(), SSDPResultData_get_Param(), SSDPResultData_set_Cookie(), SSDPResultData_set_CtrlptCallback(), and SSDPResultData_set_Param().
Referenced by SSDPResultData_dup().
SSDPResultData_delete()
UPNP_EXPORT_SPEC void SSDPResultData_delete (SSDPResultData * p)
Destructor
References UpnpDiscovery_delete().
Referenced by send_search_result(), and ssdp_handle_ctrlpt_msg().
SSDPResultData_dup()
UPNP_EXPORT_SPEC SSDPResultData * SSDPResultData_dup (const SSDPResultData * p)
Copy Constructor
References SSDPResultData_assign(), and SSDPResultData_new().
SSDPResultData_get_Cookie()
UPNP_EXPORT_SPEC void * SSDPResultData_get_Cookie (const SSDPResultData * p)
SSDPResultData_get_Cookie
Referenced by SSDPResultData_assign().
SSDPResultData_get_CtrlptCallback()
UPNP_EXPORT_SPEC Upnp_FunPtr SSDPResultData_get_CtrlptCallback (const SSDPResultData * p)
SSDPResultData_get_CtrlptCallback
Referenced by SSDPResultData_assign().
SSDPResultData_get_Param()
UPNP_EXPORT_SPEC const UpnpDiscovery * SSDPResultData_get_Param (const SSDPResultData * p)
SSDPResultData_get_Param
Referenced by SSDPResultData_assign().
SSDPResultData_new()
UPNP_EXPORT_SPEC SSDPResultData * SSDPResultData_new ()
Constructor
References UpnpDiscovery_new().
Referenced by ssdp_handle_ctrlpt_msg(), and SSDPResultData_dup().
SSDPResultData_set_Cookie()
UPNP_EXPORT_SPEC int SSDPResultData_set_Cookie (SSDPResultData * p, void * n)
SSDPResultData_set_Cookie
Referenced by ssdp_handle_ctrlpt_msg(), and SSDPResultData_assign().
SSDPResultData_set_CtrlptCallback()
UPNP_EXPORT_SPEC int SSDPResultData_set_CtrlptCallback (SSDPResultData * p, Upnp_FunPtr n)
SSDPResultData_set_CtrlptCallback
Referenced by ssdp_handle_ctrlpt_msg(), and SSDPResultData_assign().
SSDPResultData_set_Param()
UPNP_EXPORT_SPEC int SSDPResultData_set_Param (SSDPResultData * p, const UpnpDiscovery * n)
SSDPResultData_set_Param
References UpnpDiscovery_delete(), and UpnpDiscovery_dup().
Referenced by ssdp_handle_ctrlpt_msg(), and SSDPResultData_assign().